# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMouseTracking(True)
        MainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/motor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_splitter = QtWidgets.QSplitter(self.centralwidget)
        self.main_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.main_splitter.setObjectName("main_splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.main_splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.nc_code_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.nc_code_layout.setContentsMargins(0, 0, 0, 0)
        self.nc_code_layout.setObjectName("nc_code_layout")
        self.file_option_layout = QtWidgets.QHBoxLayout()
        self.file_option_layout.setObjectName("file_option_layout")
        self.nc_file_path = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.nc_file_path.setObjectName("nc_file_path")
        self.file_option_layout.addWidget(self.nc_file_path)
        self.nc_load_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/load_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nc_load_button.setIcon(icon1)
        self.nc_load_button.setObjectName("nc_load_button")
        self.file_option_layout.addWidget(self.nc_load_button)
        self.nc_save_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/save_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nc_save_button.setIcon(icon2)
        self.nc_save_button.setObjectName("nc_save_button")
        self.file_option_layout.addWidget(self.nc_save_button)
        self.nc_code_layout.addLayout(self.file_option_layout)
        self.compiler_layout = QtWidgets.QHBoxLayout()
        self.compiler_layout.setObjectName("compiler_layout")
        self.re_compiler = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.re_compiler.setObjectName("re_compiler")
        self.compiler_layout.addWidget(self.re_compiler)
        self.nc_compile = QtWidgets.QPushButton(self.verticalLayoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/merge.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nc_compile.setIcon(icon3)
        self.nc_compile.setObjectName("nc_compile")
        self.compiler_layout.addWidget(self.nc_compile)
        self.nc_code_layout.addLayout(self.compiler_layout)
        self.right_splitter = QtWidgets.QSplitter(self.main_splitter)
        self.right_splitter.setOrientation(QtCore.Qt.Vertical)
        self.right_splitter.setObjectName("right_splitter")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.right_splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.parameter_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.parameter_layout.setContentsMargins(0, 0, 0, 0)
        self.parameter_layout.setObjectName("parameter_layout")
        self.chart_tab_widget = QtWidgets.QTabWidget(self.right_splitter)
        self.chart_tab_widget.setObjectName("chart_tab_widget")
        self.pos_tab = QtWidgets.QWidget()
        self.pos_tab.setObjectName("pos_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pos_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.chart_tab_widget.addTab(self.pos_tab, "")
        self.velocity_tab = QtWidgets.QWidget()
        self.velocity_tab.setObjectName("velocity_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.velocity_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.chart_tab_widget.addTab(self.velocity_tab, "")
        self.accelerate_tab = QtWidgets.QWidget()
        self.accelerate_tab.setObjectName("accelerate_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.accelerate_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.chart_tab_widget.addTab(self.accelerate_tab, "")
        self.verticalLayout.addWidget(self.main_splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.chart_tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Motion control"))
        self.nc_load_button.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.nc_save_button.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.chart_tab_widget.setTabText(self.chart_tab_widget.indexOf(self.pos_tab), _translate("MainWindow", "Position"))
        self.chart_tab_widget.setTabText(self.chart_tab_widget.indexOf(self.velocity_tab), _translate("MainWindow", "Velocity"))
        self.chart_tab_widget.setTabText(self.chart_tab_widget.indexOf(self.accelerate_tab), _translate("MainWindow", "Accelerate"))

import icons_rc
